ros__parameters:
  vehicle_name: hatchback
  wheel_base: 2.6
  wheel_tread: 1.55
  wheel_radius: 0.32
  wheel_width: 0.21
  front_overhang: 0.85
  rear_overhang: 0.75
  left_overhang: 0.16
  right_overhang: 0.16
  ground_offset: 0.15
  vehicle_height: 1.5
  vehicle_width: 1.8699999999999999
  vehicle_length: 4.2
