[package]
name = "ssu2_simulator"
version = "0.0.0"
edition = "2021"

[dependencies]
rclrs = "0.6"
rosidl_runtime_rs = "0.5"

ssu2_planning_msgs = "*"

# PRESERVED_JINJA2_CODEGEN_START

# PRESERVED_JINJA2_CODEGEN_END