ros__parameters:
  vehicle_name: sport_car
  wheel_base: 2.6
  wheel_tread: 1.7
  wheel_radius: 0.35
  wheel_width: 0.28
  front_overhang: 1.0
  rear_overhang: 0.9
  left_overhang: 0.22
  right_overhang: 0.22
  ground_offset: 0.1
  vehicle_height: 1.2
  vehicle_width: 2.14
  vehicle_length: 4.5
