# https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/control/preset/default_preset.yaml
launch:
  # controller
  - arg:
      name: trajectory_follower_mode
      default: trajectory_follower_node
      # option: trajectory_follower_node
      #         smart_mpc_trajectory_follower
      #         none

  # external_cmd selector/converter
  - arg:
      name: launch_external_cmd_selector
      default: "false"
  - arg:
      name: launch_external_cmd_converter
      default: "false"

  # optional control checkers
  - arg:
      name: launch_lane_departure_checker
      default: "false"
  - arg:
      name: launch_control_validator
      default: "false"
  - arg:
      name: launch_autonomous_emergency_braking
      default: "false"
  - arg:
      name: launch_collision_detector
      default: "false"
  - arg:
      name: launch_obstacle_collision_checker
      default: "false"
  - arg:
      name: launch_predicted_path_checker
      default: "false"
  - arg:
      name: launch_control_evaluator
      default: "false"