$schema: "http://json-schema.org/draft-07/schema#"
$id: "/schema/metadata"
title: MetaConfig

type: object
properties:
  maintainers:
    type: array
    items:
      $ref: "#/definitions/person"
  authors:
    type: array
    items:
      $ref: "#/definitions/person"
  license:
    type: string
  cmake_version:
    type: string
  rust_edition:
    type: string
  pkg_default_version:
    type: string
  workspace_path:
    type: string
  assets_path:
    type: string
  data_path:
    type: string
  
definitions:
  person:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
    required:
      - name